# month to season mapping
seasons:
  'W': [ 1, 2, 12 ]
  'SP': [ 3, 4, 5 ]
  'S': [ 6, 7, 8 ]
  'F': [ 9, 10, 11 ]

# only one region in this model
regions: 
  - 'NAmerica'

# Canadian provinces to subregions mapping
subregions_dictionary:
  'WS': [ 'BC', 'AB' ]
  'MW': [ 'SAS', 'MAN' ]
  'OT': [ 'ONT' ]
  'QC': [ 'QC' ]
  'AT': [ 'NB', 'NS', 'PEI', 'NL' ]

# Canadian subregions without mapping
subregions_list:
  - 'WS'
  - 'MW'
  - 'OT'
  - 'QC'
  - 'AT'

# Initial year used in model (inclusive)
start_year: 2019

# Final year used in model (inclusive)
end_year: 2050

# types of emissions
emissions:
  - 'CO2'

# master list of techs
techs_master:
  - 'BIO' # Biomass
  - 'CCG' # Gas Combined Cycle 
  - 'CTG' # Gas Combustion Turbine
  - 'COA' # Coal
  - 'COC' # Coal CCS
  - 'HYD' # Hydro 
  - 'SPV' # Solar
  - 'URN' # Nuclear
  - 'WND' # Wind
   #'P2G' # Power to Gas
   #'FCL' # Fuel Cell

# list of renewable technologies
rnw_techs:
  - 'HYD' # Hydro 
  - 'SPV' # Solar
  - 'WND' # Wind
  - 'BIO' # Biomass

# list of mining technologies
mine_techs:
  - 'COA' # Coal
  - 'GAS' # Gas
  - 'URN' # Nuclear

# list of variable technologies
variable_techs:
  - 'SPV'
  - 'WND'

# list of storage technologies (In the future may have 'TNK' # Tank)
sto_techs: []

# mapping of technologies to fuels
tech_to_fuel:
  'BIO': 'BIO'
  'CCG': 'GAS'
  'CTG': 'GAS'
  'COA': 'COA'
  'COC': 'COA'
  'HYD': 'HYD'
  'SPV': 'SPV'
  'URN': 'URN'
  'WND': 'WND'
 #'P2G': 'ELC' # Power to Gas
 #'FCL': 'HY2' # Fuel Cell

 # tech mapping USA Name -> Our Name
 usa_tech_map:
  'BIOPP': 'BIO'   # Biomass
  'NGCC': 'CCG'    # Gas Combind Cycle 
  'NGCT': 'CTG'    # Gas Combustion Turbine
  'COALPP': 'COA'  # Coal
  'COALCCS': 'COC' # Coal CCS
  'HYDROPP': 'HYD' # Hydro 
  'PV': 'SPV'      # Solar
  'NUC': 'URN'     # Nuclear
  'WINDPP': 'WND'  # Wind

# dictionary holding excel sheet name to parameter names
excel_to_parameter:
  'SpecifiedAnnualDemand(r,f,y)': 'SpecifiedAnnualDemand'
  'SpecifiedDemandProfile(r,f,l,y)': 'SpecifiedDemandProfile'
  'CapacityToActivityUnit(r,t)': 'CapacityToActivityUnit'
  'CapacityFactor(r,t,l,y)': 'CapacityFactor'
  'OperationalLife(r,t)': 'OperationalLife'
  'ResidualCapacity(r,t,y)': 'ResidualCapacity'
  'InputActivityRatio(r,t,f,m,y)': 'InputActivityRatio'
  'OutputActivityRatio(r,t,f,m,y)': 'OutputActivityRatio'
  'CapitalCost(r,t,y)': 'CapitalCost'
  'VariableCost(r,t,m,y)': 'VariableCost'
  'FixedCost(r,t,y)': 'FixedCost'
  'TotalAnnualMaxCapacity(r,t,y)': 'TotalAnnualMaxCapacity'
  'ReserveMarginInTagTech(r,t,y)': 'ReserveMarginTagTechnology'
  'ReserveMarginInTagFuel(r,f,y)': 'ReserveMarginTagFuel'
  'ReserveMargin(r,y)': 'ReserveMargin'
  'RETagTechnology(r,t,y)': 'RETagTechnology'
  'EmisionActivityRatio(r,t,e,m,y)': 'EmissionActivityRatio'