name: Pylint

on: 
    push:
    pull_request:
      branches: main

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Lint code
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        PYTHON_PYLINT_CONFIG_FILE: .pylintrc
        VALIDATE_PYTHON: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


